#!/usr/bin/env bash
#Transfer file from Client to Server
argc=$# # $#- returns the size of the input array
if [[ $argc == 4 ]]
then
    PATH_TO_FILE=$1
    IP=$2
    USERNAME=$3
    PATH_TO_SSH_KEY=$4
    scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$PATH_TO_FILE" "$USERNAME@$IP:~/"
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
