#!/usr/bin/env bash
# Configure redirect page
config_file='/etc/nginx/sites-available/default'
redirect_file='/var/www/html/redirect_me.html'
echo "Moved Permanently" > $redirect_file
sed -i '/location /c\
	location /redirect_me/ {\
		return 301 redirect_me.html;\
	}\
\
	location / {
' $config_file
