#!/usr/bin/env bash
# Configure redirect page on new web server
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo ufw allow ssh
sudo ufw allow 'Nginx Full'
sudo ufw enable
config_file='/etc/nginx/sites-available/default'
redirect_file='/var/www/html/redirect_me.html'
echo "Moved Permanently" > $redirect_file
sed -i '/location /c\
	location /redirect_me/ {\
		return 301 redirect_me.html;\
	}\
\
	location / {
' $config_file
