#!/usr/bin/env bash
#Install NGINX Web Server and prepare redirect
sudo su
apt-get update
apt-get -y install nginx ufw
ufw allow 'Nginx Full'
ufw allow 'OpenSSH'
install -m 755 /var/www/html/index.html 
echo "server {
        listen 80;
        server_name _;

        root /var/www/html;
        index index.html;

        location / {
                index.html;
        }

        location /redirect_me {
                return 301 Moved Permanently;
        }
}" > /etc/nginx/sites-available/default