#!/usr/bin/env bash
# Configure custom 404 page on new web server
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo ufw allow ssh
sudo ufw allow 'Nginx Full'
sudo ufw enable
config_file='/etc/nginx/sites-available/default'
_404file='/var/www/html/404.html'
echo "Ceci n'est pas une page" > $_404file
sed -i '/location /c\
	error_page 404 /404.html;\
	location = /404.html {\
		root 404.html;\
		internal;\
	}\
\
	location / {
' $config_file
