#!/usr/bin/env bash
# Configure 404 Page
#----------------------------------
# Step 1: Prepare 404 Page
#----------------------------------
wp_root="/var/www/html"
sudo touch "$wp_root"/404.html
echo "Ceci n'est pas une page" | sudo tee "$wp_root/404.html"

#----------------------------------
# Step 2: Configure Nginx WebServer
#----------------------------------
nginx_config="/etc/nginx/sites-available/default"
ln=$(($(grep -n -m 1 "location /redirect_me {" $nginx_config| cut -d ':' -f 1) +3)) #Get line number for ammendment insertion
appendment='\
    error_page 404 /404.html;\
'
sudo sed -i "$ln a $appendment" $nginx_config

#----------------------------------
# Step 3: Restart Nginx WebServer
#----------------------------------
sudo service nginx restart

