#!/usr/bin/env bash
# Fix nginx to listen on port 80

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

sudo cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    add_header X-Served-By \$hostname;

    location / {
        try_files \$uri \$uri/ =404;
    }
} 
EOF

sudo service nginx restart