#!/usr/bin/env bash
# Fix nginx to listen on port 80
sudo docker run -dit --name nginx-fix -p 80:80 ubuntu:latest /bin/bash
sudo docker exec nginx-fix apt-get update
sudo docker exec nginx-fix apt-get install -y nginx
