#!/usr/bin/env bash
# Fix nginx to listen on port 80
sudo docker run -d --name nginx-fix -p 80:80 ubuntu:latest
sudo docker exec nginx-fix "apt-get update"
sudo docker exec nginx-fix "apt-get install -y nginx curl net-tools"
