#!/usr/bin/env bash
# Displays Numbers from 1 - 10. Notifies if number is unlucky
ite=1
while [ $ite -lt 101 ]
do 
	if [[ $((ite%3)) == 0 && $((ite%5)) == 0 ]]
	then
		echo "FizzBuzz"
	elif [[ $((ite%3)) == 0 ]]
	then
		echo "Fizz"
	elif [[ $((ite%5)) == 0 ]]
	then
		echo "Buzz"
	else
		echo "${ite}"
	fi
	((ite++))
done
