#!/usr/bin/env bash
# Displays Numbers from 1 - 10. Notifies if number is unlucky
ite=1
while [ $ite -lt 11 ]
do 
	if [[ $ite == 4 ]]
	then
		echo "bad luck"
	elif [[ $ite == 8 ]]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((ite++))
done
