#!/usr/bin/env bash
# Displays time from 00:00 to 12:59
min=1
hour=0
while [ $hour -lt 13 ]
do 
	echo "Hour: ${hour}"
	while [ $min -lt 60 ]
	do
		echo "${min}"
		((min++))
	done
	((min = 1))
	((hour++))
done
