#!/usr/bin/env bash
#--------------------------------------------------------------------
# Install Firewall and Configure to listen on only ports: 22 443 80
#--------------------------------------------------------------------
sudo apt-get update
sudo apt-get install ufw
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
sudo service ufw restart
