#!/usr/bin/env bash
# Change localhost
old_localhost='127.0.0.1'
new_localhost='127.0.0.2'
hosts_file='./hosts'
copy_file='./hosts.new'
cp $hosts_file $copy_file
sed -i "s/$old_localhost/$new_localhost/" $copy_file
sed -i '$a 8.8.8.8	facebook.com' $copy_file
cp -f $copy_file $hosts_file
rm $copy_file
